### ISSUE TITLE
broad peaks

### ISSUE THREAD

**Issue by PoisonAlien** [InesdeSantiago/BaalChIP#1]
Hi,

Can this be used for broad peaks such as H3K27Ac and super enhancers to see if its on single allele or both allele ? Are there any caveats considering these peaks are broader ? I was writing my own script to do so then I came across your package (looks very interesting).

**Comment by InesdeSantiago** [comment]
Hi!
Yes it can be used for any region, as long as you have a list of regions in
a bed format.
I have tested and published the vignette with TF and FAIRE-seq  but I also
tested with histone data and it works ok. The software computes the allelic
ratio of SNPs within those regions, then it will perform the statistical
test to see if the read counts are biased to any of the alleles.

For broad peaks, I wouldn't use the simulation filter (named filterIntbias)
which was designed for TF type of data.
best,
ines

**Comment by PoisonAlien** [comment]
Got it! just wanted to make sure. 

I have another question. How do you choose heterozygous SNP's (from your vignette) ? I was planning on calling variants and choosing all high QC heterozygous variants, but in the example it seems all are dbSNP entries. How were they chosen ? Sorry if this has been touched in vignette or in manuscript and I missed it.

**Comment by InesdeSantiago** [comment]
good! :-)
I chose only the ones on dbSNP because I wanted to get their coordinates
and the data I had (downloaded from ENCODE) did not included SNP
coordinates.
But you can chose heterozygous SNPs in any way that makes sense to your
study as long as you organise them in the right format (ID CHROM POS REF
ALT and RAF(Raf is optional)).
Best,
ines

**Comment by PoisonAlien** [comment]
Got it :)
